# LLM Server
LLM_BASE_URL=http://10.202.1.3:8000/v1
LLM_MODEL=/models/Qwen/Qwen3-Coder-40B-A3B-Instruct-FP8

# MCP Ports
ADB_MCP_PORT=5001
CONFLUENCE_MCP_PORT=5002
SQLITE_MCP_PORT=5003

# API
ORCHESTRATOR_PORT=8080

# Device Settings
DEFAULT_DEVICE_UNLOCK_PIN=1234

# Confluence
CONFLUENCE_URL=https://your-confluence.atlassian.net
CONFLUENCE_USERNAME=your-email@company.com
CONFLUENCE_API_TOKEN=your-token

# Logging
LOG_LEVEL=INFO
DEBUG_MODE=false
